package Vista;

import Modelo.ConexionBD;
import Modelo.Empleados;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class frmPrincipal extends javax.swing.JFrame {

    Empleados emp = new Empleados();
    private ImageIcon imagen;
    private Icon icono;

    /**
     * Creates new form Principal
     */
    public frmPrincipal() {
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.pintarImagen(jLabel1, "src/Imagenes/portadaFarmacia.jpg");
        Timer tiempo = new Timer(100, new frmPrincipal.horas());
        tiempo.start();
    }

    class horas implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Date fecha = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date sistHora = new Date();
            String pmAm = "hh:mm:ss a";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar hoy = Calendar.getInstance();
            lblFechaHora.setText(sdf.format(fecha) + "   " + String.format(formato.format(sistHora), hoy));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new rojeru_san.RSButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuGeneral = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        menuEmpleado = new javax.swing.JMenu();
        menuCompra = new javax.swing.JMenu();
        menuVenta = new javax.swing.JMenu();
        menuProveedor = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenu();
        menuMedicamentos = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();
        menuReport = new javax.swing.JMenu();
        subMenuClientes = new javax.swing.JMenuItem();
        subMenuVentas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuIndicador = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Farmacia");
        setBackground(new java.awt.Color(102, 153, 255));
        setFocusableWindowState(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enfermera.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, 280, 510));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cruz_Roja.svg.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, 140, 160));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("\"TUFARMA\" ");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, 60));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 660));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, 150, 30));

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 610, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario Conectado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 120, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha y Hora:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 600, 120, 20));

        lblFechaHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, 230, 30));

        lblRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 150, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rol de Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 550, 120, 20));

        menuGeneral.setBackground(new java.awt.Color(255, 255, 255));
        menuGeneral.setForeground(new java.awt.Color(255, 0, 0));
        menuGeneral.setFocusable(false);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        menuCliente.setText("Cliente              ");
        menuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClienteMouseClicked(evt);
            }
        });
        menuGeneral.add(menuCliente);

        menuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/farmaceutico.png"))); // NOI18N
        menuEmpleado.setText("Empleado            ");
        menuEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEmpleadoMouseClicked(evt);
            }
        });
        menuGeneral.add(menuEmpleado);

        menuCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OrdenCompra.png"))); // NOI18N
        menuCompra.setText("Compra          ");
        menuCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCompraMouseClicked(evt);
            }
        });
        menuGeneral.add(menuCompra);

        menuVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentaMedicina.png"))); // NOI18N
        menuVenta.setText(" Venta                   ");
        menuVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVentaMouseClicked(evt);
            }
        });
        menuGeneral.add(menuVenta);

        menuProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedor.png"))); // NOI18N
        menuProveedor.setText("Proveedor            ");
        menuProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProveedorMouseClicked(evt);
            }
        });
        menuGeneral.add(menuProveedor);

        menuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Categorias.png"))); // NOI18N
        menuCategoria.setText("Categoria          ");
        menuCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCategoriaMouseClicked(evt);
            }
        });
        menuGeneral.add(menuCategoria);

        menuMedicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MedicamentosLista.png"))); // NOI18N
        menuMedicamentos.setText("Medicamentos      ");
        menuMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMedicamentosMouseClicked(evt);
            }
        });
        menuGeneral.add(menuMedicamentos);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N
        menuReportes.setText("Reportes e Indicadores");
        menuReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportesMouseClicked(evt);
            }
        });

        menuReport.setText("Reportes");

        subMenuClientes.setText("Clientes");
        subMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuClientesActionPerformed(evt);
            }
        });
        menuReport.add(subMenuClientes);

        subMenuVentas.setText("Ventas");
        subMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuVentasActionPerformed(evt);
            }
        });
        menuReport.add(subMenuVentas);

        menuReportes.add(menuReport);
        menuReportes.add(jSeparator1);

        menuIndicador.setText("Indicadores");
        menuIndicador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIndicadorMouseClicked(evt);
            }
        });
        menuReportes.add(menuIndicador);

        menuGeneral.add(menuReportes);

        setJMenuBar(menuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        // TODO add your handling code here:
        int eleccion = JOptionPane.showConfirmDialog(null, "Seguro que quiere cerrar sesion?");
        if (eleccion == 0) {
            ModuloLogin.L.setVisible(true);
            this.setVisible(false);
        }
        ModuloLogin.L.txtUsuario.setText("");
        ModuloLogin.L.txtPassword.setText("");
        ModuloLogin.L.txtUsuario.requestFocus();
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void menuIndicadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIndicadorMouseClicked
        ModuloIndicadores ind = new ModuloIndicadores(this, true);
        ind.setVisible(true);
    }//GEN-LAST:event_menuIndicadorMouseClicked

    private void subMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuVentasActionPerformed
        // TODO add your handling code here:
        try {
            ConexionBD con = new ConexionBD();
            Connection cn = con.getConexion();

            JasperReport reporte = null;
            String path = "src\\Reportes\\reporteVentas.jasper";
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, cn);

            JasperViewer view = new JasperViewer(jprint, false);

            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_subMenuVentasActionPerformed

    private void subMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuClientesActionPerformed
        // TODO add your handling code here:
        try {
            ConexionBD con = new ConexionBD();
            Connection cn = con.getConexion();

            JasperReport reporte = null;
            String path = "src\\Reportes\\reporteClientes.jasper";
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, cn);

            JasperViewer view = new JasperViewer(jprint, false);

            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_subMenuClientesActionPerformed

    private void menuMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMedicamentosMouseClicked
        // TODO add your handling code here:
        if (lblRol.getText().equals("Administrador")) {
            menuMedicamentos.setEnabled(true);
            ModuloMedicamentos medi = new ModuloMedicamentos(this, true);
            medi.setVisible(true);
        } else if (lblRol.getText().equals("Farmaceutico")) {
            menuMedicamentos.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }

    }//GEN-LAST:event_menuMedicamentosMouseClicked

    private void menuCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoriaMouseClicked
        // TODO add your handling code here:
        if (lblRol.getText().equals("Administrador")) {
            menuCategoria.setEnabled(true);
            ModuloCategorias cat = new ModuloCategorias(this, true);
            cat.setVisible(true);
        } else if (lblRol.getText().equals("Farmaceutico")) {
            menuCategoria.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }

    }//GEN-LAST:event_menuCategoriaMouseClicked

    private void menuProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProveedorMouseClicked
        // TODO add your handling code here:
        if (lblRol.getText().equals("Administrador")) {
            menuProveedor.setEnabled(true);
            ModuloProveedores prov = new ModuloProveedores(this, true);
            prov.setVisible(true);
        } else if (lblRol.getText().equals("Farmaceutico")) {
            menuProveedor.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }

    }//GEN-LAST:event_menuProveedorMouseClicked

    private void menuVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVentaMouseClicked
        // TODO add your handling code here:
        if (lblRol.getText().equals("Administrador")) {
            menuVenta.setEnabled(true);
            ModuloVentas vent = new ModuloVentas(new JDialog(), true);
            vent.setVisible(true);
        } else if (lblRol.getText().equals("Farmaceutico")) {
            menuVenta.setEnabled(true);
            ModuloVentas vent = new ModuloVentas(new JDialog(), true);
            vent.setVisible(true);
        }

    }//GEN-LAST:event_menuVentaMouseClicked

    private void menuCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCompraMouseClicked
        // TODO add your handling code here:
        if (lblRol.getText().equals("Administrador")) {
            menuCompra.setEnabled(true);
            ModuloCompras comp = new ModuloCompras(this, true);
            comp.setVisible(true);
        } else if (lblRol.getText().equals("Farmaceutico")) {
            menuCompra.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }

    }//GEN-LAST:event_menuCompraMouseClicked

    private void menuEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmpleadoMouseClicked
        // TODO add your handling code here:
        if (lblRol.getText().equals("Administrador")) {
            menuEmpleado.setEnabled(true);
            ModuloEmpleados emp = new ModuloEmpleados(this, true);
            emp.setVisible(true);
        } else if (lblRol.getText().equals("Farmaceutico")) {
            menuEmpleado.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_menuEmpleadoMouseClicked

    private void menuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClienteMouseClicked
        // TODO add your handling code here:
        if (lblRol.getText().equals("Administrador")) {
            menuCliente.setEnabled(true);
            ModuloCliente cli = new ModuloCliente(this, true);
            cli.setVisible(true);
        } else if (lblRol.getText().equals("Farmaceutico")) {
            menuCliente.setEnabled(true);
            ModuloCliente cli = new ModuloCliente(this, true);
            cli.setVisible(true);
        }

    }//GEN-LAST:event_menuClienteMouseClicked

    private void menuReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportesMouseClicked
        // TODO add your handling code here:
        if (lblRol.getText().equals("Administrador")) {
            menuReportes.setEnabled(true);
            menuReport.setVisible(true);
            menuIndicador.setVisible(true);
        } else if (lblRol.getText().equals("Farmaceutico")) {
            menuReportes.setEnabled(false);
            menuReport.setVisible(false);
            menuIndicador.setVisible(false);
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_menuReportesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPrincipal frame = new frmPrincipal();
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }

    private void pintarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnCerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JLabel lblFechaHora;
    public javax.swing.JLabel lblRol;
    public javax.swing.JLabel lblUsuario;
    public javax.swing.JMenu menuCategoria;
    public javax.swing.JMenu menuCliente;
    public javax.swing.JMenu menuCompra;
    public javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenuBar menuGeneral;
    public javax.swing.JMenu menuIndicador;
    public javax.swing.JMenu menuMedicamentos;
    public javax.swing.JMenu menuProveedor;
    public javax.swing.JMenu menuReport;
    public javax.swing.JMenu menuReportes;
    public javax.swing.JMenu menuVenta;
    public javax.swing.JMenuItem subMenuClientes;
    public javax.swing.JMenuItem subMenuVentas;
    // End of variables declaration//GEN-END:variables

    public void opcionesMenu(){
        if(emp.getNom_rol().equals("Administrador")){
            menuCliente.setEnabled(true);
            menuEmpleado.setEnabled(true);
            menuCompra.setEnabled(true);
            menuVenta.setEnabled(true);
            menuProveedor.setEnabled(true);
            menuCategoria.setEnabled(true);
            menuMedicamentos.setEnabled(true);
            menuReportes.setEnabled(true);
        }else if(emp.getNom_rol().equals("Farmaceutico")){
            menuCliente.setEnabled(true);
            menuEmpleado.setEnabled(false);
            menuCompra.setEnabled(false);
            menuVenta.setEnabled(true);
            menuProveedor.setEnabled(false);
            menuCategoria.setEnabled(false);
            menuMedicamentos.setEnabled(false);
            menuReportes.setEnabled(false);
        }
    }
    
    public static frmPrincipal P = new frmPrincipal();
}
