/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCliente;
import Modelo.Client;
import Modelo.ConexionBD;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jordie
 */
public class ModuloCliente extends javax.swing.JDialog {

    ConexionBD cn = new ConexionBD();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Client cli = new Client();
    ControladorCliente concli = new ControladorCliente();

    public ModuloCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        concli.Listar_Clientes(tablaCliente);
        anchosTabla();
        concli.Listar_Combo_Distritos(cboDistrito);
        jbtnEliminar.setEnabled(false);
        jbtnModificar.setEnabled(false);
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblcod = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jbtnNuevo = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        cboDistrito = new javax.swing.JComboBox<>();
        lblcod1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        dtFecha = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcod.setForeground(new java.awt.Color(255, 255, 255));
        lblcod.setText("Codigo");
        jPanel1.add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO CLIENTE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 360, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Direccion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Distrito");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesIconos/buscar.png"))); // NOI18N
        jLabel4.setText("Buscar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 120, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FechaRegistro");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtCod.setEditable(false);
        txtCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodMouseClicked(evt);
            }
        });
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 160, -1));
        jPanel1.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 30, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 250, 20));

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesIconos/nuevo.png"))); // NOI18N
        jbtnNuevo.setText("Limpiar");
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, 40));

        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesIconos/guardar.png"))); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, 40));

        jbtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesIconos/eliminar.png"))); // NOI18N
        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 110, 40));

        jbtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesIconos/editar.png"))); // NOI18N
        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 120, 40));

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Codigo", "DNI_RUC", "Nombre", "Direccion", "Distrito", "Sexo", "Telefono", "Fecha_Registro"
            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 80, 840, 450));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Documento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, -1));

        jPanel1.add(cboDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, -1));

        lblcod1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcod1.setForeground(new java.awt.Color(255, 255, 255));
        lblcod1.setText("ID");
        jPanel1.add(lblcod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtID.setEditable(false);
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMouseClicked(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 30, -1));
        jPanel1.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 160, -1));
        jPanel1.add(dtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sexo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jTabbedPane1.addTab("Registro Clientes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        
        if (txtDocumento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese algun valor");
        } else {
            
            String f = "dd/MM/yyyy";
            java.util.Date fechita = dtFecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(f);

            cli.setDni_ruc(txtDocumento.getText());
            cli.setNom_cli(txtNombre.getText());
            cli.setDir_cli(txtDireccion.getText());
            cli.setCod_dis(cboDistrito.getSelectedIndex());
            cli.setSexo(txtSexo.getText());
            cli.setTelefono(txtTelefono1.getText());
            cli.setFecha_registro(sdf.format(fechita));

            concli.Insertar_Clientes();
            concli.Listar_Clientes(tablaCliente);
            anchosTabla();
            limpiarFormulario();
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        // TODO add your handling code here:
        jbtnGuardar.setEnabled(false);
        jbtnEliminar.setEnabled(true);
        jbtnModificar.setEnabled(true);
        int fila = tablaCliente.rowAtPoint(evt.getPoint());
        txtID.setText(tablaCliente.getValueAt(fila, 0).toString());
        txtCod.setText(tablaCliente.getValueAt(fila, 1).toString());
        txtDocumento.setText(tablaCliente.getValueAt(fila, 2).toString());
        txtNombre.setText(tablaCliente.getValueAt(fila, 3).toString());
        txtDireccion.setText(tablaCliente.getValueAt(fila, 4).toString());
        cboDistrito.getModel().setSelectedItem(String.valueOf(tablaCliente.getModel().getValueAt(fila, 5).toString()));
        txtSexo.setText(tablaCliente.getValueAt(fila, 6).toString());
        txtTelefono1.setText(tablaCliente.getValueAt(fila, 7).toString());
        dtFecha.setDate(Date.valueOf(tablaCliente.getValueAt(fila, 8).toString()));

    }//GEN-LAST:event_tablaClienteMouseClicked

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        
        if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la tabla");
        } else {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el registro?");
            if (pregunta == 0) {
                cli.setId_cli(Integer.parseInt(txtID.getText()));

                concli.Eliminar_Cliente();
                concli.Listar_Clientes(tablaCliente);
                anchosTabla();
                limpiarFormulario();
            }
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
        jbtnGuardar.setEnabled(true);
        jbtnEliminar.setEnabled(false);
        jbtnModificar.setEnabled(false);
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed

        if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la tabla");
        } else {
            String f = "dd/MM/yyyy";
            java.util.Date fechita = dtFecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(f);

            cli.setId_cli(Integer.parseInt(txtID.getText()));
            cli.setDni_ruc(txtDocumento.getText());
            cli.setNom_cli(txtNombre.getText());
            cli.setDir_cli(txtDireccion.getText());
            cli.setCod_dis(cboDistrito.getSelectedIndex());
            cli.setSexo(txtSexo.getText());
            cli.setTelefono(txtTelefono1.getText());
            cli.setFecha_registro(sdf.format(fechita));

            concli.Modificar_Cliente();
            concli.Listar_Clientes(tablaCliente);
            anchosTabla();
            limpiarFormulario();
        }
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void txtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "No se puede Editar!!");
    }//GEN-LAST:event_txtIDMouseClicked

    private void txtCodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "No se puede Editar!!");
    }//GEN-LAST:event_txtCodMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        cli.setNom_cli(txtBuscar.getText()+'%');
        concli.Buscar_Cliente(tablaCliente);
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModuloCliente dialog = new ModuloCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboDistrito;
    private com.toedter.calendar.JDateChooser dtFecha;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton jbtnEliminar;
    public javax.swing.JButton jbtnGuardar;
    public javax.swing.JButton jbtnModificar;
    public javax.swing.JButton jbtnNuevo;
    public javax.swing.JLabel lblcod;
    public javax.swing.JLabel lblcod1;
    private javax.swing.JTable tablaCliente;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCod;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtDocumento;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtSexo;
    public javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        txtID.setText("");
        txtCod.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtDocumento.setText("");
        txtSexo.setText("");
        txtTelefono1.setText("");
        txtSexo.setText("");
        cboDistrito.setSelectedIndex(0);
        dtFecha.setCalendar(null);
    }
    
    
    private void anchosTabla(){
        int[] anchos = {25,60,80,150,200,80,25,70,100};
        
        for (int i = 0; i < tablaCliente.getColumnCount(); i++) {
            tablaCliente.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]); 
        }
    }

}
